name: Continuous Integration

on:
  push:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10]

    steps:
      # checkout code base
      uses: actions/checkout@v2

      # install python
      name: Setup Python ${{ matrix.python-version }}
      uses: action/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

      # install python dependencies
      name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r reqiurements.txt;

      # install actual unit tests
      name: Test with unittest
      run: |
        python3 -m unittest tests.test_root
